### ISSUE TITLE
	instance system.adapter.nuki-extended.0 terminated with code 6

### ISSUE THREAD

**Issue by sansonifabio** [iobroker-community-adapters/ioBroker.nuki-extended#250]
**Describe the bug**  

Seit kurzem geht der nuki adpater auf Rot ohne mein dazutun. Dabei kommen dann diese Fehlermeldungen die ich erst nach dem Update auf v2.6.1 bekomme habe. 
Wenn ich den Adapter dann wieder per Hand starte, wird wieder alles grün und er läuft ganz normal ohne Fehler.
Herzliche Grüße
Fabio

The nuki adpater recently went red without my doing anything. Then these error messages come up, which I only got after the update to v2.6.1.
If I start the adapter again by hand, everything turns green again and it runs normally without any errors.

****Screenshots & Logfiles****  
host.nuc
2022-06-13 06:09:39.073	error	instance system.adapter.nuki-extended.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.nuc
2022-06-13 06:09:39.073	error	Caught by controller[1]: at processImmediate (internal/timers.js:464:21)
host.nuc
2022-06-13 06:09:39.073	error	Caught by controller[1]: at Immediate.Async.drainQueues [as _onImmediate] (/opt/iobroker/node_modules/bluebird/js/release/async.js:15:14)
host.nuc
2022-06-13 06:09:39.072	error	Caught by controller[1]: at Async._drainQueues (/opt/iobroker/node_modules/bluebird/js/release/async.js:102:5)
host.nuc
2022-06-13 06:09:39.072	error	Caught by controller[1]: at _drainQueue (/opt/iobroker/node_modules/bluebird/js/release/async.js:86:9)
host.nuc
2022-06-13 06:09:39.072	error	Caught by controller[1]: at _drainQueueStep (/opt/iobroker/node_modules/bluebird/js/release/async.js:93:12)
host.nuc
2022-06-13 06:09:39.072	error	Caught by controller[1]: at Promise._settlePromises (/opt/iobroker/node_modules/bluebird/js/release/promise.js:725:18)
host.nuc
2022-06-13 06:09:39.072	error	Caught by controller[1]: at Promise._settlePromise0 (/opt/iobroker/node_modules/bluebird/js/release/promise.js:649:10)
host.nuc
2022-06-13 06:09:39.072	error	Caught by controller[1]: at Promise._settlePromise (/opt/iobroker/node_modules/bluebird/js/release/promise.js:604:18)
host.nuc
2022-06-13 06:09:39.072	error	Caught by controller[1]: at Promise._settlePromiseFromHandler (/opt/iobroker/node_modules/bluebird/js/release/promise.js:547:31)
host.nuc
2022-06-13 06:09:39.072	error	Caught by controller[1]: at tryCatcher (/opt/iobroker/node_modules/bluebird/js/release/util.js:16:23)
host.nuc
2022-06-13 06:09:39.072	error	Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.nuki-extended/nuki-extended.js:602:13
host.nuc
2022-06-13 06:09:39.072	error	Caught by controller[1]: at setAction (/opt/iobroker/node_modules/iobroker.nuki-extended/nuki-extended.js:618:14)
host.nuc
2022-06-13 06:09:39.071	error	Caught by controller[1]: TypeError: nukiWebApi.setAction is not a function
host.nuc
2022-06-13 06:09:39.070	error	Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

nuki-extended.0
2022-06-13 06:09:38.537	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

nuki-extended.0
2022-06-13 06:09:38.536	info	terminating

nuki-extended.0
2022-06-13 06:09:38.536	info	Adapter stopped und unloaded.

nuki-extended.0
2022-06-13 06:09:38.531	error	nukiWebApi.setAction is not a function

nuki-extended.0
2022-06-13 06:09:38.531	error	TypeError: nukiWebApi.setAction is not a function at setAction (/opt/iobroker/node_modules/iobroker.nuki-extended/nuki-extended.js:618:14) at /opt/iobroker/node_modules/iobroker.nuki-extended/nuki-extended.js:602:13 at tryCatcher (/opt/iobroker/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/opt/iobroker/node_modules/bluebird/js/release/promise.js:547:31) at Promise._settlePromise (/opt/iobroker/node_modules/bluebird/js/release/promise.js:604:18) at Promise._settlePromise0 (/opt/iobroker/node_modules/bluebird/js/release/promise.js:649:10) at Promise._settlePromises (/opt/iobroker/node_modules/bluebird/js/release/promise.js:725:18) at _drainQueueStep (/opt/iobroker/node_modules/bluebird/js/release/async.js:93:12) at _drainQueue (/opt/iobroker/node_modules/bluebird/js/release/async.js:86:9) at Async._drainQueues (/opt/iobroker/node_modules/bluebird/js/release/async.js:102:5) at Immediate.Async.drainQueues [as _onImmediate] (/opt/iobroker/node_modules/bluebird/js/release/async.js:15:14) at processImmediate (internal/timers.js:464:21)

nuki-extended.0
2022-06-13 06:09:38.530	error	unhandled promise rejection: nukiWebApi.setAction is not a function

nuki-extended.0
2022-06-13 06:09:38.530	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

****Versions:****  
nuki-extended.0V v2.6.1
Node.js v14.19.3
NPM 6.14.17
4.0.23

**Comment by Apollon77** [comment]
fixed in 2.6.3

**Comment by sansonifabio** [comment]
**Vielen Dank. ;-)**
